### ISSUE TITLE
javascript code freezing browser after 3 food eatings

### ISSUE THREAD

**Issue by ishankhare07** [ishankhare07/snake#1]
how to reproduce: 
1. Play the game at [ishankare07.github.io/snake](http://ishankhare07.github.io/snake)
2. Make 3 successful food eats.
3. As soon as you eat the 4th food, browser freezes

possible reason : most probably an infinite loop/recursion, which is not easy to dig in as everything freezes, even the chrome dev. console

**Comment by ishankhare07** [comment]
the problem is probably with the addUnit function, the loop goes infinite after 3 units

**Comment by branespace** [comment]
I humbly submit https://github.com/ishankhare07/snake/pull/2 as a solution to your problem.  Details within.

**Comment by ishankhare07** [comment]
thanks a lot @branespace !
